// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// match_terms
List match_terms(const List& tokens, const CharacterVector& terms, const LogicalVector& isword, const IntegerVector& dim, const bool& complete);
RcppExport SEXP _lingmatch_match_terms(SEXP tokensSEXP, SEXP termsSEXP, SEXP iswordSEXP, SEXP dimSEXP, SEXP completeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type tokens(tokensSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type terms(termsSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type isword(iswordSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< const bool& >::type complete(completeSEXP);
    rcpp_result_gen = Rcpp::wrap(match_terms(tokens, terms, isword, dim, complete));
    return rcpp_result_gen;
END_RCPP
}
// vector_similarity
NumericVector vector_similarity(NumericVector& a, NumericVector& b, const IntegerVector& metrics);
RcppExport SEXP _lingmatch_vector_similarity(SEXP aSEXP, SEXP bSEXP, SEXP metricsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type metrics(metricsSEXP);
    rcpp_result_gen = Rcpp::wrap(vector_similarity(a, b, metrics));
    return rcpp_result_gen;
END_RCPP
}
// calculate_similarities
List calculate_similarities(const S4& m, const RObject& comp, int& type, const IntegerVector& metrics);
RcppExport SEXP _lingmatch_calculate_similarities(SEXP mSEXP, SEXP compSEXP, SEXP typeSEXP, SEXP metricsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const RObject& >::type comp(compSEXP);
    Rcpp::traits::input_parameter< int& >::type type(typeSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type metrics(metricsSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_similarities(m, comp, type, metrics));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lingmatch_match_terms", (DL_FUNC) &_lingmatch_match_terms, 5},
    {"_lingmatch_vector_similarity", (DL_FUNC) &_lingmatch_vector_similarity, 3},
    {"_lingmatch_calculate_similarities", (DL_FUNC) &_lingmatch_calculate_similarities, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_lingmatch(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
