# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

match_terms <- function(tokens, terms, isword, dim) {
    .Call(`_lingmatch_match_terms`, tokens, terms, isword, dim)
}

vector_similarity <- function(a, b, metrics) {
    .Call(`_lingmatch_vector_similarity`, a, b, metrics)
}

calculate_similarities <- function(m, comp, type, metrics) {
    .Call(`_lingmatch_calculate_similarities`, m, comp, type, metrics)
}

