# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

match_terms <- function(tokens, terms, isword, dim, complete, tokensonly) {
    .Call(`_lingmatch_match_terms`, tokens, terms, isword, dim, complete, tokensonly)
}

vector_similarity <- function(a, b, metrics) {
    .Call(`_lingmatch_vector_similarity`, a, b, metrics)
}

calculate_similarities <- function(m, comp, type, metrics) {
    .Call(`_lingmatch_calculate_similarities`, m, comp, type, metrics)
}

reformat_embedding <- function(infile, outfile, sep = ' ', digits = 9L, remove = "", term_check = "^[a-zA-Z]+$|^['a-zA-Z][a-zA-Z.'\\/-]*[a-zA-Z.]$", verbose = FALSE) {
    invisible(.Call(`_lingmatch_reformat_embedding`, infile, outfile, sep, digits, remove, term_check, verbose))
}

extract_indices <- function(indices, file, sep = ' ') {
    .Call(`_lingmatch_extract_indices`, indices, file, sep)
}

extract_matches <- function(terms, file, sep = ' ') {
    .Call(`_lingmatch_extract_matches`, terms, file, sep)
}

pattern_search <- function(texts, patterns, terms, fixed, exclusive) {
    .Call(`_lingmatch_pattern_search`, texts, patterns, terms, fixed, exclusive)
}

